const LOGIN_EMAIL = 'EMAIL';
const LOGIN_PASSWORD = 'PASSWORD';
const LOGIN_REMEMBER = 'REMEMBER';

const REGISTER_FIRST_NAME = 'FIRST_NAME';
const REGISTER_LAST_NAME = 'LAST_NAME';
const REGISTER_EMAIL = 'EMAIL';
const REGISTER_PASSWORD = 'PASSWORD';
const REGISTER_RE_PASSWORD = 'RE-PASSWORD';

export { LOGIN_EMAIL, LOGIN_PASSWORD, LOGIN_REMEMBER };

export { REGISTER_FIRST_NAME, REGISTER_LAST_NAME, REGISTER_EMAIL, REGISTER_PASSWORD, REGISTER_RE_PASSWORD };